### PR TITLE
Fix MyBinder environment to certain commit

### PR DESCRIPTION
**Pull request by fmaussion**
This makes sure that the MyBinder link will always work the same, regardless of how the packages below are updated (e.g. OGGM and upstream packages).

This will work as long as MyBinder keeps an image in memory (I don't know how long that is).

We should continue this discussion about reproducibility on slack one day

### CODE REVIEW

**Comment by ehultee** [comment]
To clarify: The commit message on d97f57d reads "Fix MyBinder environment to certain commit"--this means _of OGGM_, right?  So the notebooks can change, but MyBinder will always launch with OGGM, Numpy, Matplotlib etc. as they are 1 Aug 2019?

**Comment by fmaussion** [comment]
> So the notebooks can change, but MyBinder will always launch with OGGM, Numpy, Matplotlib etc. as they are 1 Aug 2019?

This would be the goal. I changed the mybinder link from https://mybinder.org/v2/gh/OGGM/oggm-edu-r2d/master to https://mybinder.org/v2/gh/OGGM/oggm-edu-r2d/0bbeba7c025a6a7190e17c7c1f816841ef6a923b, effectively fixing the environment to [June 28](https://github.com/OGGM/oggm-edu-r2d/commit/0bbeba7c025a6a7190e17c7c1f816841ef6a923b)

*However*, this is unfortunately not guaranteed to be fixed forever. It will work, as long as MyBinder remembers having built that commit already, and I'm not sure that MyBinder actually guarantees that.

In order to ensure true reproducibility we should do something else (really specify the tag of an already built image we really own): I might do that as well, but this is more work and I have to think/read about it first.

**Comment by fmaussion** [comment]
> So the notebooks can change

Yes they can. They are not pinned right now, but thanks to github it's always easy to go back to old states. Going back to old environments is extremely hard though :-(

**Comment by ehultee** [comment]
Okay.  So the anticipated future situation we are addressing is that some function of the upstream packages needed by these notebooks changes, and suddenly the unsuspecting user gets a bunch of errors they won't know how to fix.  Yes?

Good idea to set this up for now.  For the long term, the reproducibility question is interesting, but if it's a lot of work for you to set up an image, we might prioritize 
(1) having instructors check notebook function and report/debug errors before they teach
(2) revisiting these N times per year to ensure function
...
each of which is relatively low effort.

I'll merge and we can discuss long term plans later.

**Comment by fmaussion** [comment]
I agree, but the problem we have *right now* is that the images we build currently are broken: they produce wrong plots for reasons which are out of our control :disappointed:

**Pull request merged**
