### PR TITLE
Same for NB4

### PR DESCRIPTION
**Pull request by fmaussion**
I noticed that on one cell you store output during a run loop that you don't use for any plot -> it that on purpose?

Would you like to add this pic at the end of the nb?

img

### CODE REVIEW

**Comment by ehultee** [comment]
I understand why you made this PR but I don't understand the text that goes along with it...seems to be treating two different topics

**Comment by fmaussion** [comment]
Yes it does - nevermind the comment, just merge.

**Comment by ehultee** [comment]
Okay.  The answer to the question is that I don't recall exactly what I stored (probably ELA position?) but I probably did meant to plot it and didn't mean to.  Yes we can add that plot (in a different commit). Merging the ; correction now.

**Comment by ehultee** [comment]
Probably I did mean to plot it and didn't remember to do it *

...sleepy

**Pull request merged**
